language: php
dist: xenial

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - COMPOSER_ALLOW_XDEBUG=0

jobs:
  include:
    - stage: test
      name: "Test installing the lowest dependencies"
      php: 7.3
      install:
        - phpenv config-rm xdebug.ini || true
        - composer update --prefer-lowest --prefer-stable --no-interaction --no-suggest
      script:
        - php vendor/bin/phpunit
        - php vendor/bin/phpstan analyze src tests --level=3

    - stage: test
      php: 7.1
      install:
        - phpenv config-rm xdebug.ini || true
        - composer update --no-interaction --no-suggest
      script:
        - php vendor/bin/phpunit
        - php vendor/bin/phpstan analyze src tests --level=3

    - stage: test
      php: 7.2
      install:
        - phpenv config-rm xdebug.ini || true
        - composer update --no-interaction --no-suggest
      script:
        - php vendor/bin/phpunit
        - php vendor/bin/phpstan analyze src tests --level=3

    - stage: test
      php: 7.3
      install:
        - phpenv config-rm xdebug.ini || true
        - composer update --no-interaction --no-suggest
      script:
        - phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml
        - php vendor/bin/phpstan analyze src tests --level=3
      after_script:
        - php vendor/bin/php-coveralls -o coveralls-upload.json -x coverage.xml

    - stage: test
      if: 'type = cron'
      php: 7.4snapshot
      install:
        - phpenv config-rm xdebug.ini || true
        - composer update --no-interaction --no-suggest
      script:
        - php vendor/bin/phpunit
        - php vendor/bin/phpstan analyze src tests --level=3

    - stage: test
      if: 'type = cron'
      php: nightly
      install:
        - phpenv config-rm xdebug.ini || true
        - composer update --no-interaction --no-suggest
      script:
        - php vendor/bin/phpunit
        - php vendor/bin/phpstan analyze src tests --level=3

  allow_failures:
    - php: 7.4snapshot
    - php: nightly
