<?php

/*
 * This file is part of Contao.
 *
 * Copyright (c) 2005-2015 Leo Feyer
 *
 * @license LGPL-3.0+
 */

namespace Contao\Image;

use Imagine\Image\BoxInterface;
use Imagine\Image\PointInterface;

/**
 * Resize coordinates generated by the ResizeCalculator.
 *
 * @author Martin Auswöger <martin@auswoeger.com>
 */
interface ResizeCoordinatesInterface
{
    /**
     * Constructor.
     *
     * @param BoxInterface   $size      The target size
     * @param PointInterface $cropStart The crop start coordinate
     * @param BoxInterface   $cropSize  The crop size
     */
    public function __construct(
        BoxInterface $size,
        PointInterface $cropStart,
        BoxInterface $cropSize
    );

    /**
     * Gets the size.
     *
     * @return BoxInterface
     */
    public function getSize();

    /**
     * Gets the crop start coordinate.
     *
     * @return PointInterface
     */
    public function getCropStart();

    /**
     * Gets the crop size.
     *
     * @return BoxInterface
     */
    public function getCropSize();

    /**
     * Gets a hash of the coordinates.
     *
     * @return string
     */
    public function getHash();

    /**
     * Compares the coordinates with another ResizeCoordinates or Box object.
     *
     * @param self|BoxInterface $coordinates The object to compare
     *
     * @return bool
     */
    public function equals($coordinates);
}
